version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: quicket-api-dev
    volumes:
      - .:/app
      - go-mode:/go/pkg/mod
      - go-cache:/root/.cache/go-build
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - quicket-net
  mysql:
    image: mysql:8.0
    container_name: quicket-mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - quicket-net
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - mysql
    restart: no
    networks:
      - quicket-net
networks:
  quicket-net:
    driver: bridge
volumes:
  mysql_data_dev:
  go-mod:
  go-cache:
