// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/anrisys/quicket/internal/booking"
	"github.com/anrisys/quicket/internal/event"
	"github.com/anrisys/quicket/internal/payment"
	"github.com/anrisys/quicket/internal/user"
	"github.com/anrisys/quicket/pkg/config"
	"github.com/anrisys/quicket/pkg/config/logger"
	"github.com/anrisys/quicket/pkg/database"
	"github.com/anrisys/quicket/pkg/security"
	"github.com/anrisys/quicket/pkg/token"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	appConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.MySQLDB(appConfig)
	if err != nil {
		return nil, err
	}
	zerologLogger := logger.NewZerolog(appConfig)
	userRepository := user.NewUserRepository(db, zerologLogger)
	accountSecurity := security.NewAccountSecurity(appConfig)
	generator := token.NewGenerator(appConfig)
	userService := user.NewUserService(userRepository, zerologLogger, accountSecurity, generator)
	userHandler := user.NewUserHandler(userService, zerologLogger)
	gormRepository := booking.NewGormRepository(db, zerologLogger)
	eventRepository := event.NewEventRepository(db, zerologLogger)
	eventService := event.NewEventService(eventRepository, userService, zerologLogger)
	paymentGormRepository := payment.NewRepository(db, zerologLogger)
	paymentService := payment.NewPaymentService(paymentGormRepository, zerologLogger)
	service := booking.NewService(gormRepository, eventService, zerologLogger, paymentService, userService)
	handler := booking.NewHandler(service, zerologLogger)
	eventHandler := event.NewEventHandler(eventService, zerologLogger)
	app := &App{
		Config:         appConfig,
		UserHandler:    userHandler,
		BookingHandler: handler,
		EventHandler:   eventHandler,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config         *config.AppConfig
	UserHandler    *user.UserHandler
	BookingHandler *booking.Handler
	EventHandler   *event.EventHandler
}
