// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"quicket/booking-service/internal"
	"quicket/booking-service/pkg/config"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	repo := internal.NewRepo()
	srv := internal.Newsrv(repo)
	handler := internal.NewHandler(srv)
	app := &App{
		Config:  configConfig,
		Handler: handler,
	}
	return app, nil
}
