version: "3.8"

services:
  monolith-api:
    build:
      context: ../monolith
      dockerfile: Dockerfile.dev
    container_name: quicket-api-monolith
    volumes:
      - ../monolith:/app
      - quicket-monolith-go-mod:/go/pkg/mod
    ports:
      - "8080:8080"
    env_file:
      - ../monolith/.env
    depends_on:
      - monolith-mysql
    networks:
      - quicket-net
  monolith-mysql:
    image: mysql:8.0
    container_name: quicket-monolith-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MONOLITH_DB_PASSWORD}
      MYSQL_DATABASE: ${MONOLITH_DB_NAME}
      MYSQL_USER: ${MONOLITH_DB_USER}
      MYSQL_PASSWORD: ${MONOLITH_DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - quicket-monolith-mysql-data:/var/lib/mysql
    networks:
      - quicket-net
  monolith-migrate:
    image: migrate/migrate
    container_name: quicket-monolith-migrate
    env_file:
      - ../monolith/.env
    volumes:
      - ../monolith/migrations:/migrations
    depends_on:
      - monolith-mysql
    restart: no
    networks:
      - quicket-net
  user-service-api:
    build:
      context: ../user-service
      dockerfile: Dockerfile.dev
    container_name: quicket-user-service-api
    volumes:
      - ../user-service:/app
      - quicket-user-service-go-mod:/go/pkg/mod
    env_file:
      - ../user-service/.env
    ports: -"8081:8081"
    depends_on:
      - user-service-mysql
    networks:
      - quicket-net
  user-service-mysql:
    image: mysql:8.0
    container_name: user-service-mysql
    restart: always
    env_file:
      - ../user-service/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      MYSQL_DATABASE: ${USER_SERVICE_DB_NAME}
      MYSQL_USER: ${USER_SERVICE_DB_USER}
      MYSQL_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - quicket-user-service-mysql:/var/lib/mysql
    networks:
      - quicket-net
  user-service-migrate:
    image: migrate/migrate
    container_name: quicket-user-service-migrate
    env_file:
      - ../user-service/.env
    volumes:
      - ../user-service/migrations: ./migrations
    depends_on:
      - user-service-mysql
    restart: no
    networks:
      - quicket-net
networks:
  quicket-net:
    driver: bridge
volumes:
  quicket-monolith-mysql-data:
  quicket-monolith-go-mod:
  quicket-user-service-go-mod:
  quicket-user-service-mysql:
