services:
  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: quicket-api-gateway
    ports:
      - "8080:80"
    depends_on:
      user-api:
        condition: service_healthy
    networks:
      - quicket-net
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries-1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  quicket-base-dev:
    build:
      context: ../docker
      dockerfile: base-dev.Dockerfile
  user-api:
    build:
      context: ../user-service
      dockerfile: Dockerfile.dev
    container_name: quicket-user-api
    volumes:
      - ../user-service:/app
      - quicket-user-go-mod:/go/pkg/mod
    env_file:
      - ./.env
    ports:
      - "8081:8081"
    depends_on:
      user-mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - quicket-net
  user-mysql:
    image: mysql:8.0.43-debian
    container_name: user-mysql
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${USER_MYSQL_DB_NAME}
      MYSQL_USER: ${USER_MYSQL_USER}
      MYSQL_PASSWORD: ${USER_MYSQL_PASSWORD}
    ports:
      - "${USER_MYSQL_EXTERNAL_PORT}:3306"
    volumes:
      - quicket-user-mysql:/var/lib/mysql
    networks:
      - quicket-net
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${USER_MYSQL_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
networks:
  quicket-net:
    driver: bridge
    name: quicket-net
volumes:
  quicket-user-go-mod:
  quicket-user-mysql:
