FROM golang:1.24

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/cosmtrek/air@latest && \
    go install github.com/swaggo/swag/cmd/swag@latest

COPY . .

EXPOSE 8081

CMD ["air", "-c", ".air.toml"]