basePath: /api/v1/bookings
host: localhost:8082
info:
  contact:
    email: anris.y.simorangkir@gmail.com
    name: Quicket Support
    url: https://github.com/anrisys/quicket
  description: Bookings service API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Quicket Bookings Service API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
