// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/anrisys/quicket/user-service/internal"
	"github.com/anrisys/quicket/user-service/pkg/config"
	"github.com/anrisys/quicket/user-service/pkg/database"
	"github.com/anrisys/quicket/user-service/pkg/security"
	"github.com/anrisys/quicket/user-service/pkg/token"
)

// Injectors from wire.go:

func InitializeUserServiceApp() (*UserServiceApp, error) {
	appConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.ConnectMySQL(appConfig)
	if err != nil {
		return nil, err
	}
	logger := config.NewZerolog(appConfig)
	userRepository := internal.NewUserRepository(db, logger)
	accountSecurity := security.NewAccountSecurity(appConfig)
	tokenGenerator := token.NewTokenGenerator(appConfig)
	userService := internal.NewUserService(userRepository, logger, accountSecurity, tokenGenerator)
	userHandler := internal.NewUserHandler(userService, logger)
	userServiceApp := &UserServiceApp{
		Config:  appConfig,
		Handler: userHandler,
	}
	return userServiceApp, nil
}
