root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"
  bin = "tmp/main"
  full_bin = "./tmp/main"
  exclude_dir = ["api", "test", "migration"]

[log]
  time = true

[misc]
clean_on_exit = true