// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/anrisys/quicket/event-service/internal"
	"github.com/anrisys/quicket/event-service/pkg/config"
	"github.com/anrisys/quicket/event-service/pkg/database"
	"github.com/anrisys/quicket/event-service/pkg/redis"
)

// Injectors from wire.go:

func InitializeEventServiceApp() (*EventServiceApp, error) {
	appConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.ConnectMySQL(appConfig)
	if err != nil {
		return nil, err
	}
	logger := config.NewZerolog(appConfig)
	eventRepository := internal.NewEventRepository(db, logger)
	userServiceClient := internal.NewUserServiceClient(appConfig)
	configRedis, err := config.LoadRedisConfig()
	if err != nil {
		return nil, err
	}
	client := redis.NewClient(configRedis)
	eventService := internal.NewEventService(eventRepository, userServiceClient, logger, client)
	eventHandler := internal.NewEventHandler(eventService, logger)
	eventServiceApp := &EventServiceApp{
		Config:  appConfig,
		Handler: eventHandler,
	}
	return eventServiceApp, nil
}
