// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/anrisys/quicket/event-service/internal"
	"github.com/anrisys/quicket/event-service/pkg/config"
	"github.com/anrisys/quicket/event-service/pkg/database"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.ConnectMySQL(configConfig)
	if err != nil {
		return nil, err
	}
	logger := config.NewZerolog(configConfig)
	eventRepository := internal.NewEventRepository(db, logger)
	userServiceClient := internal.NewUserServiceClient(configConfig)
	redisClient := database.NewRedisClient(configConfig)
	eventService := internal.NewEventService(eventRepository, userServiceClient, logger, redisClient)
	eventHandler := internal.NewEventHandler(eventService, logger)
	app := &App{
		Config:  configConfig,
		Handler: eventHandler,
	}
	return app, nil
}
